params:
  - params.yaml

stages:
  ######################################################################################
  # CONTAINER BUILDING -----------------------------------------------------------------
  ######################################################################################

  # build_container:
  #   cmd: >-
  #     ${project_root}/stages/build_container.sh
  #     ${container.type}
  #     ${container.name}
  #     ${container.docker_tag}
  #     ${container.def}
  #     ${container.image}
  #   deps:
  #     - ${container.def}
  #     - pyproject.toml
  #     - poetry.lock
  #     - README.md
  #     - ${project_root}/stages/build_container.sh
  #   params:
  #     - container
  #   outs:
  #     - ${project_root}/${container.image}:
  #         persist: true

  ######################################################################################
  # RES-IND., PFT-DEP. STAGES ----------------------------------------------------------
  ######################################################################################

  # get_TRY_mean_traits:
  #   cmd: >-
  #     ${project_root}/stages/get_TRY_mean_traits.sh
  #     ${container.type}
  #     ${container.name}
  #     ${container.docker_tag}
  #     ${container.image}
  #     "poetry run python src/data/build_try_traits.py"
  #   deps:
  #     - src/data/build_try_traits.py
  #   params:
  #     - try_version
  #     - trydb
  #     - PFT
  #   outs:
  #     - ${interim_dir}/${trydb.interim.dir}/${trydb.interim.filtered}:
  #         persist: true
  #     - ${interim_dir}/${trydb.interim.dir}/${trydb.interim.transformer_fn}:
  #         persist: true
  #     - ${interim_dir}/${trydb.interim.dir}/${trydb.interim.pca_fn}:
  #         persist: true

  build_traits:
    cmd: python ${project_root}/src/data/build_hydraulic_traits.py --params ${product_dir}/params.yaml
    deps:
      - ${project_root}/src/data/build_hydraulic_traits.py
      - ${project_root}/${traits.raw}
      - ${project_root}/src/utils/match_pfts.py
    outs:
      - ${project_root}/${traits.interim_out}
      # Also outputs transformer pickle IF transform is not None, but as it is a small,
      # conditional output, it is OK not to track it with DVC.

  filter_gbif:
    cmd: python ${project_root}/src/data/filter_gbif.py --params ${product_dir}/params.yaml
    deps:
      - ${project_root}/src/data/filter_gbif.py
      - ${project_root}/${gbif.raw_fp}
      - ${project_root}/${traits.interim_out}
    outs:
      - ${project_root}/${gbif.filtered.out_dir}/${trait_type}/${gbif.filtered.fp}
      - ${project_root}/${gbif.filtered.out_dir}/${trait_type}/${gbif.filtered.report_fp}
      - ${project_root}/${gbif.filtered.out_dir}/${trait_type}/${gbif.filtered.density_plot_fp}

  filter_splot:
    cmd: python ${project_root}/src/data/filter_splot.py --params ${product_dir}/params.yaml
    deps:
      - ${project_root}/src/data/filter_splot.py
      - ${project_root}/data/raw/${splot.raw.dir}
      - ${project_root}/${traits.interim_out}
    outs:
      - ${project_root}/${interim_dir}/${splot.interim.dir}/${splot.interim.filtered}
      - ${project_root}/${interim_dir}/${splot.interim.dir}/${splot.interim.report}

  # match_gbif_pfts:
  #   cmd: >-
  #     stages/match_gbif_pfts.sh
  #     ${container.type}
  #     ${container.name}
  #     ${container.docker_tag}
  #     ${container.image}
  #     "poetry run python src/data/match_gbif_pfts.py"
  #   deps:
  #     - src/data/match_gbif_pfts.py
  #     - ${gbif.raw_fp}
  #     - ${raw_dir}/${trydb.raw.pfts}
  #   params:
  #     - datasets.Y.gbif
  #     - gbif.raw.dir
  #     - gbif.interim.dir
  #     - gbif.interim.matched
  #     - PFT
  #   outs:
  #     - ${interim_dir}/${gbif.interim.dir}/${gbif.interim.matched}:
  #         persist: true

  # extract_splot:
  #   cmd: >-
  #     stages/extract_splot.sh
  #     ${container.type}
  #     ${container.name}
  #     ${container.docker_tag}
  #     ${container.image}
  #     "poetry run python src/data/extract_splot.py"
  #   deps:
  #     - src/data/extract_splot.py
  #     - ${raw_dir}/${datasets.Y.splot}
  #   params:
  #     - datasets.Y.splot
  #     - splot.interim.dir
  #   outs:
  #     - ${project_root}/${interim_dir}/${splot.interim.dir}/${splot.interim.extracted}:
  #         persist: true

  standardize_other_products:
    cmd: python src/data/standardize_other_products.py
    deps:
      - src/data/standardize_other_products.py
      - ${raw_dir}/other-trait-maps
    outs:
      - ${interim_dir}/other_trait_maps:
          persist: false

  ######################################################################################
  # RES-DEP., PFT-IND. -----------------------------------------------------------------
  ######################################################################################

  harmonize_eo_data:
    cmd: python src/data/harmonize_eo_data.py
    deps:
      - src/data/harmonize_eo_data.py
    params:
      - model_res
      - mask
      - datasets.X
      - base_resolution
      - target_resolution
      - eo_data.interim.dir
      - worldclim.bio_vars
    outs:
      - ${interim_dir}/${eo_data.interim.dir}/${model_res}:
          persist: false

  build_predict:
    cmd: python src/features/featurize_predict.py
    deps:
      - src/features/featurize_predict.py
      - ${interim_dir}/${eo_data.interim.dir}/${model_res}
    params:
      - model_res
      - train.dir
      - eo_data.interim.dir
      - eo_data.predict.dir
      - eo_data.predict.mask_fn
      - eo_data.predict.imputed_fn
    outs:
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.mask_fn}:
          persist: false
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.imputed_fn}:
          persist: false


  ######################################################################################
  # RES DEP., PFT-DEP. STAGES ----------------------------------------------------------
  ######################################################################################
  
  build_gbif_maps:
    cmd: python ${project_root}/stages/build_gbif_maps.py --params params.yaml
    deps:
      - ${project_root}/src/data/build_gbif_map.py
      - ${project_root}/${gbif.filtered.out_dir}/${trait_type}/${gbif.filtered.fp}
      - ${project_root}/${traits.interim_out}
    outs:
      - ${project_root}/${gbif.maps.out_dir}/${product_code}:
          persist: false 

  build_splot_maps:
    cmd: >-
      stages/build_splot_maps_parallel.sh
    deps:
      - src/data/build_splot_maps.py
      - ${interim_dir}/${splot.interim.dir}/${splot.interim.extracted}
      - ${raw_dir}/${trydb.raw.pfts}
      - ${interim_dir}/${trydb.interim.dir}/${trydb.interim.filtered}
    params:
      - splot.interim
      - model_res
      - PFT
      - target_resolution
      - datasets.Y.traits
    outs:
      - ${interim_dir}/${splot.interim.dir}/${splot.interim.traits}/${PFT}/${model_res}:
          persist: false

  build_y:
    cmd: >-
      stages/build_y.sh
      ${container.type}
      ${container.name}
      ${container.docker_tag}
      ${container.image}
      "poetry run python src/features/build_y.py"
    deps:
      - src/features/build_y.py
      - ${interim_dir}/${gbif.interim.dir}/${gbif.interim.traits}/${PFT}/${model_res}
      - ${interim_dir}/${splot.interim.dir}/${splot.interim.traits}/${PFT}/${model_res}
    params:
      - datasets.Y.trait_stat
      - datasets.Y.traits
    outs:
      - ${train.dir}/${PFT}/${model_res}/${train.Y.fn}

  calculate_spatial_autocorr:
    cmd: python src/features/calc_spatial_autocorr_gpu.py
    deps:
      - src/features/calc_spatial_autocorr.py
      - ${train.dir}/${PFT}/${model_res}/${train.Y.fn}
    params:
      - train.spatial_autocorr
      - calc_spatial_autocorr
    outs:
      - ${train.dir}/${PFT}/${model_res}/${train.spatial_autocorr}

  build_cv_splits:
    cmd: python src/features/skcv_splits.py -o
    deps:
      - src/features/skcv_splits.py
      - ${train.dir}/${PFT}/${model_res}/${train.Y.fn}
      - ${train.dir}/${PFT}/${model_res}/${train.spatial_autocorr}
    params:
      - train.cv_splits
    outs:
      - ${train.dir}/${PFT}/${model_res}/${train.cv_splits.dir}:
          persist: false

  train_models:
    cmd: python src/models/train_models.py -r && python src/models/cv_stats.py
    deps:
      - src/models/train_models.py
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.mask_fn}
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.imputed_fn}
      - ${train.dir}/${PFT}/${model_res}/${train.Y.fn}
      - ${train.dir}/${PFT}/${model_res}/${train.cv_splits.dir}
      - ${interim_dir}/${trydb.interim.dir}/${trydb.interim.transformer_fn}
    params:
      - train.arch
      - autogluon
      - datasets.Y.traits
    outs:
      - ${models.dir}/${PFT}/${model_res}:
          persist: true
  
  aoa:
    cmd: python src/analysis/aoa.py
    deps:
      - src/analysis/aoa.py
      - ${train.dir}/${PFT}/${model_res}/${train.Y.fn}
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.imputed_fn}
      - ${models.dir}/${PFT}/${model_res}  # Feature importance
    params:
      - datasets.Y.traits
      - aoa
    outs:
      - ${processed.dir}/${PFT}/${model_res}/${aoa.dir}:
          persist: true

  predict:
    cmd: python src/models/predict_traits.py -r -v
    deps:
      - src/models/predict_traits.py
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.imputed_fn}
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.mask_fn}
      - ${models.dir}/${PFT}/${model_res}
      - ${interim_dir}/${trydb.interim.dir}/${trydb.interim.transformer_fn}
    params:
      - predict
    outs:
      - ${processed.dir}/${PFT}/${model_res}/${predict.dir}:
          persist: true

  cov:
    cmd: python src/models/predict_traits.py -r -v --cov
    deps:
      - src/models/predict_traits.py
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.imputed_fn}
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.mask_fn}
      - ${models.dir}/${PFT}/${model_res}
      - ${interim_dir}/${trydb.interim.dir}/${trydb.interim.transformer_fn}
    params:
      - predict
      - cov
    outs:
      - ${processed.dir}/${PFT}/${model_res}/${cov.dir}:
          persist: true

  build_final_product:
    cmd: python src/data/build_final_product.py -o
    deps:
      - src/data/build_final_product.py
      - reference/trait_mapping.json
      - reference/trait_stat_mapping.json
      - ${processed.dir}/${PFT}/${model_res}/${predict.dir}
      - ${processed.dir}/${PFT}/${model_res}/${cov.dir}
      - ${processed.dir}/${PFT}/${model_res}/${aoa.dir}
    params:
      - public
    outs:
      - ${processed.dir}/${PFT}/${model_res}/${public.local_dir}:
          persist: true

  aggregate_all_stats:
    cmd: python src/models/multires_stats.py -mfc
    deps:
      - src/models/multires_stats.py
      - ${models.dir}/${PFT}/${model_res}
    params:
      - analysis
  
  aggregate_aoa:
    cmd: python src/analysis/multires_aoa.py
    deps:
      - src/analysis/multires_aoa.py
      - ${processed.dir}/${PFT}/${model_res}/${aoa.dir}
  
  other_product_splot_correlation:
    cmd: python src/analysis/other_product_splot_correlation.py
    deps:
      - src/analysis/other_product_splot_correlation.py
      - ${interim_dir}/other_trait_maps
      - ${interim_dir}/${splot.interim.dir}/${splot.interim.traits}/${PFT}/${model_res}