project_root: ../../..
id: modis_wc2_soil_canopy_vodca_55km
model_res: 55km
base_resolution: 1000 # Shared best resolution of all EO datasets (used for masking)
target_resolution: 55000 # Target resolution for model training
extent: [-180, -60, 180, 90] # Extent of the final dataset
crs: "EPSG:6933" # Equal Area Cylindrical projection

landcover_mask:
  path: ../../../data/raw/esa_worldcover_v100_1km/esa_worldcover_v100_1km.tif
  keep_classes:
    - 10 # Tree cover
    - 20 # Shrubland
    - 30 # Grassland
    - 40 # Cropland
    - 60 # Bare/sparse vegetation
    - 70 # Snow and ice
    - 90 # Herbaceous wetland
    - 95 # Mangroves
    - 100 # Moss and lichen

datasets:
  X:
    canopy_height: data/raw/ETH_GlobalCanopyHeight_2020_v1_1km
    modis: data/raw/modis_sur_refl_monthly_avg_1km
    soilgrids: data/raw/soilgrids_v2-0_1km
    vodca: data/raw/vodca_mean-p5-p95_1km
    worldclim: data/raw/wc2-1_30s_bio

interim_eo_dir: ../../../data/interim/eo_data/${id}
features_X_dir: ../../../data/features/X/${id}
X_mask_fn: eo_predict_mask.parquet
X_imputed_fn: eo_predict_imputed.parquet

worldclim:
  bio_vars:
    - "1" # Annual Mean Temperature
    - "4" # Temperature Seasonality (standard deviation ×100)
    - "7" # Temperature Annual Range (BIO5-BIO6)
    - "12" # Annual Precipitation
    - "13-14" # Annual precipitation range (BIO13-BIO14)
    - "15" # Precipitation Seasonality (Coefficient of Variation)