version: "2"
project_root: "../../.."
trait_dir: "pipeline/traits/try6_no-xf"
trait_type: "try6"

traits:
  raw: data/raw/TRY_6_gapfilled_for_distribution
  zip: TRY6_gapfilled_for_distribution.zip
  zipfile_csv: TRY6_gapfilled_for_distribution/TRY6_gapfilled_filtered_2.csv.zip
  aggregation: median  # Options: "mean" or "median"
  quantile_range: [0.01, 0.99]  # Filter outliers outside 1st and 99th percentile per trait
  names:
    - X4 # Stem specific density (SSD, stem dry mass per stem fresh volume) or wood density
    - X6 # Root rooting depth
    - X13 # Leaf carbon (C) content per leaf dry mass
    - X14 # Leaf nitrogen (N) content per leaf dry mass
    - X15 # Leaf phosphorus (P) content per leaf dry mass
    - X21 # Stem diameter
    - X26 # Seed dry mass
    - X27 # Seed length
    - X46 # Leaf thickness
    - X47 # Leaf dry mass per leaf fresh mass (leaf dry matter content, LDMC)
    - X50 # Leaf nitrogen (N) content per leaf area
    - X55 # Leaf dry mass (single leaf)
    - X78 # Leaf nitrogen (N) isotope signature (delta 15N)
    - X95 # Seed germination rate (germination efficiency)
    - X138 # Seed number per reproducton unit
    - X144 # Leaf length
    - X145 # Leaf width
    - X146 # Leaf carbon/nitrogen (C/N) ratio
    - X163 # Leaf fresh mass
    - X169 # Stem conduit density (vessels and tracheids)
    - X237 # Dispersal unit length
    - X281 # Stem conduit diameter (vessels, tracheids)
    - X282 # Wood vessel element length; stem conduit (vessel and tracheids) element length
    - X289 # Wood fiber lengths
    - X297 # Wood rays per millimetre (wood ray density)
    - X614 # Fine root length per fine root dry mass (specific fine root length, SRL)
    - X1080 # Root length per root dry mass (specific root length, SRL)
    - X3106 # Plant height vegetative
    - X3114 # Leaf area (in case of compound leaves undefined if leaf or leaflet, undefined if petiole is in- or e
    - X3117 # Leaf area per leaf dry mass (specific leaf area, SLA or 1/LMA): undefined if petiole is in- or exclu
    - X3120 # Leaf water content per leaf dry mass (not saturated)
  transform: null
  pfts: data/raw/try_pfts.parquet
  pfts_threshold: 0.60
  harmonization_fp: data/raw/hydraulic_traits_matching_results_2025-10-03.gz
  harmonization_col: groNameIn
  interim_out_dir: data/interim/traits/try6_no-xf
  interim_out: data/interim/traits/try6_no-xf/try6_no-xf.parquet