project_root: ../../..
params_path: pipeline/eo_data/modis_wc2_soil_canopy_vodca_alos_1km/params.yaml
id: modis_wc2_soil_canopy_vodca_alos_1km
model_res: 1km
base_resolution: 1000 # Shared best resolution of all EO datasets (used for masking)
target_resolution: 1000 # Target resolution for model training
extent: [-180, -60, 180, 90] # Extent of the final dataset
crs: "EPSG:6933" # Equal Area Cylindrical projection
tmp_dir: tmp/eo_data
raw_dir: data/raw
dask_dashboard: ":39143"

geos:
  harmonize_eo_data:
    n_workers: 70
  build_predict:
    n_chunks: 3
    n_workers: 80
    memory_limit: 400GB
nemo:
  harmonize_eo_data:
    n_workers: 60
  nemo:
    calculate_modis_ndvi:
      n_workers: 12
  build_predict:
    n_chunks: 4
    n_workers: 60
    memory_limit: 100GB
    threads_per_worker: 2

landcover_mask:
  path: data/raw/esa_worldcover_v100_1km/esa_worldcover_v100_1km.tif
  keep_classes:
    - 10 # Tree cover
    - 20 # Shrubland
    - 30 # Grassland
    - 40 # Cropland
    - 60 # Bare/sparse vegetation
    - 70 # Snow and ice
    - 90 # Herbaceous wetland
    - 95 # Mangroves
    - 100 # Moss and lichen

datasets:
  canopy_height: data/raw/ETH_GlobalCanopyHeight_2020_v1_1km
  modis: data/raw/modis_sur_refl_monthly_avg_1km
  soilgrids: data/raw/soilgrids_v2-0_1km
  vodca: data/raw/vodca_mean-p5-p95_1km
  worldclim: data/raw/wc2-1_30s_bio
  alos: data/raw/ALOS_CHILI

interim:
  out_dir: data/interim/eo_data/modis_wc2_soil_canopy_vodca_alos_1km

x_dir: data/features/predict/modis_wc2_soil_canopy_vodca_alos_1km
x_fn: X.parquet
missing_val_thresh: 0.4

worldclim:
  bio_vars:
    - "1" # Annual Mean Temperature
    - "4" # Temperature Seasonality (standard deviation ×100)
    - "7" # Temperature Annual Range (BIO5-BIO6)
    - "12" # Annual Precipitation
    - "13-14" # Annual precipitation range (BIO13-BIO14)
    - "15" # Precipitation Seasonality (Coefficient of Variation)