params:
  - params.yaml

stages:
  harmonize_eo_data:
    cmd: python ${project_root}/stages/harmonize_eo_data.py --params params.yaml
    deps:
      - ${project_root}/src/data/harmonize_eo_data.py
    params:
      - model_res
      - landcover_mask
      - datasets
      - base_resolution
      - target_resolution
      - interim.out_dir
      - worldclim.bio_vars
    outs:
      - ${project_root}/${interim.out_dir}:
          persist: true

  build_predict:
    cmd: python ${project_root}/stages/build_predict.py --params params.yaml
    deps:
      - ${project_root}/src/features/build_predict.py
      - ${project_root}/${interim.out_dir}
    params:
      - datasets
      - interim.out_dir
      - x_dir
      - x_fn
    outs:
      - ${project_root}/${x_dir}